# Generated by Django 3.2.6 on 2021-08-28 05:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Donate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='occurence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donate',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='donate',
            name='times_donated',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
