# Generated by Django 3.2.6 on 2021-08-28 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField(blank=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('is_mission', models.BooleanField()),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('dollar_target', models.IntegerField(blank=True)),
                ('current_dollar', models.IntegerField(blank=True, default=0)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('is_shared', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Post.post')),
            ],
        ),
    ]
