# Generated by Django 3.2.6 on 2021-08-27 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
