# Generated by Django 3.2.6 on 2021-08-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('from_account_id', 'to_account_id'), name='unique_followers'),
        ),
    ]
